### ISSUE TITLE
rubygems is not a valid package for ubuntu 14.04

### ISSUE THREAD

**Issue by njbarrett** [geerlingguy/ansible-role-ruby#14]
When using this role on ubuntu 14.04 the rubygems package is not valid: see http://packages.ubuntu.com/search?keywords=rubygems

The correct package seems to be rubygems1.9.1 which works from 10.04, 12.04 & 14.04

Ideally rubygems would be installed from github or .tar.gz as suggested on the website:
https://rubygems.org/pages/download

This would ensure the latest stable rubygems which is 2.4 rather than the old versions installed through apt

**Comment by geerlingguy** [comment]
The [official Ubuntu Ruby installation guide](https://help.ubuntu.com/community/RubyOnRails#RubyGems_via_apt) shows `rubygems` as the correct package to install, and installing the version-specific package breaks this role's idempotence.

Since the recommended package for Ubuntu 14.04 is different, I've decided to go the route of #17 instead.

Thanks for pointing this out! I don't yet have an Ubuntu 14.04 server running Ruby, but now I know it'll work when installing via apt :)

**Comment by njbarrett** [comment]
Awesome, no problem and thanks for fixing.

**Comment by geerlingguy** [comment]
You're welcome! Please let me know if you have any other trouble with the role on 14.04.
